[package]
name = "norm"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"

[lib]
name = "norm"
path = "src/norm/lib.rs"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
clap_derive = "4.5.0"
