[package]
name = "normc"
version = "0.1.0"
authors = ["Vladimir Zarypov <krre31@gmail.com>"]
edition = "2021"
description = "Compiler for Norm language"
repository = "https://github.com/krre/norm-compiler"

[dependencies]
